server:
  port: 8088
  servlet:
    context-path: /recharge
debug: false
spring:
  datasource:
    url: jdbc:mysql://129.211.90.90:3306/recharge?useUnicode=true&characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: root
    password: Root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 129.211.90.90
    port: 6379
    password: redis
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 20
      min-idle: 10
    timeout: 2000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dliberty.recharge.entity
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
  tokenHead: Bearer
BASE_PATH: /export/static/file
oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAIySeB65IvOWKo
  accessKeySecret: GKQuDSKcJEYdSbkgADq9BVX3AyABff
  bucketName: mtbox
  policy:
    expire: 300 # 签名有效期(S)
  maxSize: 10 # 上传文件大小(M)
  callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
  dir:
    prefix: recharge/images/ # 上传文件夹路径前缀
app:
  weixin:
    appid: wxe67b6b7e7b50c7e1
    secret: 6e719debbc7f625339ba5f8d66f13ae4
RECHARGE:
   API:
      URL: http://apilf.bm001.com/api
   APP:
      KEY: 10001319
      SECRET: gUjpChpSnyrEr4RdURxtyx695kLE70Ar
   ACCESS:
      TOKEN: 333bdfb8339640a4b40259078a2ac442
   CALLBACK:
      URL: http://www.baidu.com